# Generated by Django 4.2.2 on 2023-07-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmployeeData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(max_length=50)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=100)),
                ("division", models.CharField(max_length=50)),
                ("building", models.IntegerField()),
                ("room", models.IntegerField()),
            ],
        ),
    ]
