# Generated by Django 4.2.2 on 2023-07-04 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_xml", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmployeeData",
        ),
    ]
